
logging:
  level:
    root: INFO
    org.springframework: WARN
    your.package.name: DEBUG
  file:
    name: /Users/kangminseung/Desktop/filebeat/docker-elk/log/myapp.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"